//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDBCompanyFile
    {
        public int FID { get; set; }
        public int CID { get; set; }
        public string Cname { get; set; }
        public string Fname { get; set; }
        public string ShareType { get; set; }
        public string OfferCode { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovalComment { get; set; }
        public string FileStorage { get; set; }
        public string ChequeOption { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isPrintFirstRecord { get; set; }
        public Nullable<bool> isPrintFirstOK { get; set; }
        public Nullable<bool> isPrintAll { get; set; }
        public string CreatedBy { get; set; }
        public byte[] FILEADD { get; set; }
    }
}
