//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDBCompany
    {
        public int CID { get; set; }
        public string CName { get; set; }
        public string AccountNumber { get; set; }
        public string ContactName { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovalComment { get; set; }
        public string CreatedBy { get; set; }
    }
}
