//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDBChequeOption
    {
        public int COID { get; set; }
        public string COName { get; set; }
        public string SignaturePath { get; set; }
    }
}
